module.exports = {
    CLOUDINARY_NAME: process.env.CLOUDINARY_NAME,
    CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
    MAIL_CHIMP_API_KEY: process.env.MAIL_CHIMP_API_KEY,
    MAIL_CHIMP_AUDIENCE_ID: process.env.MAIL_CHIMP_AUDIENCE_ID,
    FORM_URL: process.env.FORM_URL,
} 
